name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build apps
      uses: hyoo-ru/mam_build@master2
      with:
        package: gymload
